# Generated by Django 4.2.20 on 2025-07-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='hierarchy_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
