# Generated by Django 4.2.20 on 2025-07-20 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_role_hierarchy_level_alter_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visible_to_users',
            field=models.ManyToManyField(blank=True, related_name='visible_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='visible_to_roles',
            field=models.ManyToManyField(blank=True, to='chat.role'),
        ),
    ]
